name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Asegúrate de que esta es la rama correcta en GitHub
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Usa una versión compatible con Vue y Vite

      - name: Install dependencies
        run: npm install
        working-directory: mi-vue-app

      - name: Build Vue App
        run: npm run build
        working-directory: mi-vue-app

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_MOSS_0D1190310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Token para integración con GitHub
          action: "upload"
          app_location: "mi-vue-app" # Ubicación del código fuente de Vue
          api_location: "" # Si no usas Azure Functions, deja esto vacío
          output_location: "mi-vue-app/dist" # Carpeta donde se genera la build de Vue

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_MOSS_0D1190310 }}
          action: "close"
